# Generated by Django 5.2.5 on 2025-08-26 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sign_in_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('doctor_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('bmi', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('diabetes', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('hypertension', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('medication_count', models.IntegerField()),
                ('length_of_stay', models.IntegerField()),
                ('discharge_destination', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=20)),
                ('readmitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
